const allProducts = [
    {
        "id": "low-ph-good-morning",
        "title": "Low PH Good Morning Gel Cleanser",
        "description": "Nettoyant doux au pH faible.",
        "image": "../products/low-ph-good-morning/product-main.png",
        "category": "nettoyants",
        "link": "../products/low-ph-good-morning/index.html",
        "brand": "BODY & SEOUL",
        "price": "189 DHS",
        "rating": "4.8",
        "reviews": "693"
    },
    {
        "id": "revive-eye-serum",
        "title": "Revive Eye Serum : Ginseng + Retinal",
        "description": "Sérum contour des yeux au ginseng.",
        "image": "../products/revive-eye-serum/product-main.png",
        "category": "contour-yeux",
        "link": "../products/revive-eye-serum/index.html",
        "brand": "BODY & SEOUL",
        "price": "299 DHS",
        "rating": "4.7",
        "reviews": "421"
    },
    {
        "id": "relief-cream",
        "title": "345 Relief Cream",
        "description": "Crème apaisante et hydratante.",
        "image": "../products/relief-cream/product-main.png",
        "category": "cremes",
        "link": "../products/relief-cream/index.html",
        "brand": "BODY & SEOUL",
        "price": "299 DHS",
        "rating": "4.8",
        "reviews": "421"
    },
    {
        "id": "relief-sun",
        "title": "Relief Sun : Rice + Probiotics SPF50+",
        "description": "Protection solaire hydratante.",
        "image": "../products/relief-sun/product-main.png",
        "category": "protection-solaire",
        "link": "../products/relief-sun/index.html",
        "brand": "BODY & SEOUL",
        "price": "199 DHS",
        "rating": "4.8",
        "reviews": "512"
    },
    {
        "id": "hyalu-cica-sun-serum",
        "title": "Madagascar Centella Hyalu-Cica Water-Fit Sun Serum",
        "description": "Sérum solaire léger et hydratant.",
        "image": "../products/hyalu-cica-sun-serum/product-main.png",
        "category": "protection-solaire",
        "link": "../products/hyalu-cica-sun-serum/index.html",
        "brand": "BODY & SEOUL",
        "price": "229 DHS",
        "rating": "4.9",
        "reviews": "327"
    },
    {
        "id": "zero-pore-pad",
        "title": "Zero Pore Pad 2.0",
        "description": "Pads exfoliants pour pores.",
        "image": "../products/zero-pore-pad/product-main.png",
        "category": "exfoliation-pads",
        "link": "../products/zero-pore-pad/index.html",
        "brand": "BODY & SEOUL",
        "price": "179 DHS",
        "rating": "4.7",
        "reviews": "284"
    },
    {
        "id": "travel-kit",
        "title": "Madagascar Centella Travel Kit",
        "description": "Kit skincare voyage complet.",
        "image": "../products/travel-kit/product-main.png",
        "category": "kits",
        "link": "../products/travel-kit/index.html",
        "brand": "BODY & SEOUL",
        "price": "349 DHS",
        "rating": "4.8",
        "reviews": "156"
    },
    {
        "id": "Retinol Shot Tightening Serum",
        "title": "Retinol Shot Tightening Serum",
        "description": "Soin ciblé au rétinol pour lisser et raffermir la peau.",
        "image": "../products/Retinol Shot Tightening Serum/product-main.png",
        "category": "cremes",
        "link": "../products/Retinol Shot Tightening Serum/index.html",
        "brand": "BODY & SEOUL",
        "price": "249 DHS",
        "rating": "4.7",
        "reviews": "198"
    },
    {
        "id": "Celimax The -A Retinol Shot",
        "title": "Celimax The -A Retinol Shot",
        "description": "Soin retinol pour améliorer la texture et l'éclat de la peau.",
        "image": "../products/Celimax The -A Retinol Shot/product-main.png",
        "category": "cremes",
        "link": "../products/Celimax The -A Retinol Shot/index.html",
        "brand": "BODY & SEOUL",
        "price": "249 DHS",
        "rating": "4.7",
        "reviews": "203"
    },
    {
        "id": "medicube PDRN Pink Peptide Serum",
        "title": "Medicube PDRN Pink Peptide Serum",
        "description": "Sérum peptide pour une peau repulpée et lumineuse.",
        "image": "../products/medicube PDRN Pink Peptide Serum /product-main.png",
        "category": "cremes",
        "link": "../products/medicube PDRN Pink Peptide Serum /index.html",
        "brand": "BODY & SEOUL",
        "price": "289 DHS",
        "rating": "4.8",
        "reviews": "176"
    }
];
