const allProducts = [
    {
        "id": "low-ph-good-morning",
        "title": "COSRX Low pH Good Morning Gel Cleanser 150ml",
        "description": "Le Low pH Good Morning Gel Cleanser de COSRX est l'un des nettoyants visage les plus réputés de la K-Beauty, plébiscité par des millions d'utilisateurs à travers le monde. Sa formule à pH...",
        "image": "../products/low-ph-good-morning/product-main.png",
        "category": "nettoyants",
        "link": "../products/low-ph-good-morning/index.html",
        "brand": "COSRX",
        "price": "179 DHS",
        "rating": "4.8",
        "reviews": "693",
        "name": "COSRX Low pH Good Morning Gel Cleanser 150ml",
        "oldPrice": "299 DHS"
    },
    {
        "id": "revive-eye-serum",
        "title": "Beauty of Joseon Revive Eye Serum 30ml",
        "description": "Le Revive Eye Serum de Beauty of Joseon est un soin contour des yeux haute performance formulé autour de deux actifs stars : le ginseng coréen rouge, reconnu pour ses puissantes propriété...",
        "image": "../products/revive-eye-serum/product-main.png",
        "category": "contour-yeux",
        "link": "../products/revive-eye-serum/index.html",
        "brand": "Beauty of Joseon",
        "price": "229 DHS",
        "rating": "4.7",
        "reviews": "421",
        "name": "Beauty of Joseon Revive Eye Serum 30ml",
        "oldPrice": "379 DHS"
    },
    {
        "id": "relief-cream",
        "title": "Dr. Althea 345 Relief Cream 50ml",
        "description": "La 345 Relief Cream de Dr. Althea est une crème réparatrice de référence pour les peaux sensibles, réactives, sujettes aux rougeurs ou fragilisées par des soins actifs (post-rétinol, post...",
        "image": "../products/relief-cream/product-main.png",
        "category": "cremes",
        "link": "../products/relief-cream/index.html",
        "brand": "Dr. Althea",
        "price": "269 DHS",
        "rating": "4.8",
        "reviews": "421",
        "name": "Dr. Althea 345 Relief Cream 50ml",
        "oldPrice": "399 DHS"
    },
    {
        "id": "relief-sun",
        "title": "Beauty of Joseon Relief Sun SPF50+ PA++++ 50ml",
        "description": "La Beauty of Joseon Relief Sun est l'écran solaire K-Beauty le plus viral au monde, incontournable des routines beauté coréennes depuis son lancement. Formulée à SPF50+ PA++++, elle offre...",
        "image": "../products/relief-sun/product-main.png",
        "category": "protection-solaire",
        "link": "../products/relief-sun/index.html",
        "brand": "Beauty of Joseon",
        "price": "219 DHS",
        "rating": "4.8",
        "reviews": "512",
        "name": "Beauty of Joseon Relief Sun SPF50+ PA++++ 50ml",
        "oldPrice": "349 DHS"
    },
    {
        "id": "hyalu-cica-sun-serum",
        "title": "SKIN1004 Hyalu-Cica Water-Fit Sun Serum SPF50+",
        "description": "Le Hyalu-Cica Water-Fit Sun Serum de SKIN1004 redéfinit le soin solaire en combinant une protection SPF50+ PA++++ de haut niveau à un cocktail d'ingrédients hydratants et apaisants rareme...",
        "image": "../products/hyalu-cica-sun-serum/product-main.png",
        "category": "protection-solaire",
        "link": "../products/hyalu-cica-sun-serum/index.html",
        "brand": "SKIN1004",
        "price": "229 DHS",
        "rating": "4.9",
        "reviews": "327",
        "name": "SKIN1004 Hyalu-Cica Water-Fit Sun Serum SPF50+",
        "oldPrice": "349 DHS"
    },
    {
        "id": "zero-pore-pad",
        "title": "Medicube Zero Pore Pad 2.0 – 70 Pads",
        "description": "Les Zero Pore Pad 2.0 de Medicube sont des disques exfoliants bi-face hautement concentrés en un complexe d'acides (AHA + BHA + PHA) qui agissent en synergie pour une exfoliation chimique...",
        "image": "../products/zero-pore-pad/product-main.png",
        "category": "exfoliation-pads",
        "link": "../products/zero-pore-pad/index.html",
        "brand": "Medicube",
        "price": "289 DHS",
        "rating": "4.7",
        "reviews": "284",
        "name": "Medicube Zero Pore Pad 2.0 – 70 Pads",
        "oldPrice": "419 DHS"
    },
    {
        "id": "travel-kit",
        "title": "SKIN1004 Madagascar Centella Travel Kit",
        "description": "Le Madagascar Centella Travel Kit de SKIN1004 regroupe les essentiels de la gamme Centella, la référence K-Beauty pour les peaux sensibles, réactives ou déshydratées. La Centella Asiatica...",
        "image": "../products/travel-kit/product-main.png",
        "category": "kits",
        "link": "../products/travel-kit/index.html",
        "brand": "SKIN1004",
        "price": "349 DHS",
        "rating": "4.8",
        "reviews": "156",
        "name": "SKIN1004 Madagascar Centella Travel Kit",
        "oldPrice": "499 DHS"
    },
    {
        "id": "Retinol Shot Tightening Serum",
        "title": "Celimax Retinol Shot Tightening Booster 30ml",
        "description": "Le Retinol Shot Tightening Booster de Celimax est un sérum anti-âge concentré à 0,1% de rétinol, l'actif de référence mondial pour la correction des rides, des pores élargis et de la text...",
        "image": "../products/Retinol Shot Tightening Serum/product-main.png",
        "category": "cremes",
        "link": "../products/Retinol Shot Tightening Serum/index.html",
        "brand": "Celimax",
        "price": "239 DHS",
        "rating": "4.7",
        "reviews": "198",
        "name": "Celimax Retinol Shot Tightening Booster 30ml",
        "oldPrice": "320 DHS"
    },
    {
        "id": "Celimax The -A Retinol Shot",
        "title": "Celimax Vita-A Retinal Shot Tightening Booster 15ml",
        "description": "Le Vita-A Retinal Shot Tightening Booster de Celimax est un concentré anti-âge de pointe formulé au rétinal (aldéhyde de vitamine A), actif jusqu'à 11 fois plus puissant que le rétinol cl...",
        "image": "../products/Celimax The -A Retinol Shot/product-main.png",
        "category": "cremes",
        "link": "../products/Celimax The -A Retinol Shot/index.html",
        "brand": "Celimax",
        "price": "249 DHS",
        "rating": "4.7",
        "reviews": "203",
        "name": "Celimax Vita-A Retinal Shot Tightening Booster 15ml",
        "oldPrice": "320 DHS"
    },
    {
        "id": "medicube PDRN Pink Peptide Serum",
        "title": "Medicube PDRN Pink Peptide Serum 30ml",
        "description": "Le PDRN Pink Peptide Serum de Medicube est un sérum de nouvelle génération qui exploite la technologie PDRN (Polydeoxyribonucléotide), un actif bio-technologique dérivé de l'ADN de saumon...",
        "image": "../products/medicube PDRN Pink Peptide Serum /product-main.png",
        "category": "cremes",
        "link": "../products/medicube PDRN Pink Peptide Serum /index.html",
        "brand": "Medicube",
        "price": "279 DHS",
        "rating": "4.8",
        "reviews": "176",
        "name": "Medicube PDRN Pink Peptide Serum 30ml",
        "oldPrice": "399 DHS"
    }
];

window.allProducts = allProducts;
